### ISSUE TITLE
Create PIP Package

### ISSUE THREAD

**Issue by freelancing-solutions** [EodHistoricalData/python-eodhistoricaldata#12]
### PIP Packaging 

References

[packaging projects](https://packaging.python.org/tutorials/packaging-projects/)

[Flask Extensions](https://flask.palletsprojects.com/en/1.1.x/extensiondev/)

- **My contributions may cover creating a python SDK for EOD,  and also a flask extension. for the same SDK**
- **however for this to be a reality we would need to first.**

- [ ]  Increase EOD API Coverage.

- [ ]  Provide endpoints for both CSV and JSON compatible endpoints.

**Comment by deios0** [comment]
What do you mean by 'increase the coverage'? Add more APIs?
I guess it's better to support JSON only, especially for Python, JSON endpoints usually provide more information, like dividends API and we support CSV for backward compatibility now with limited functional, we do not add new fields in existing CSV endpoints, even we have it in JSON.

**Comment by freelancing-solutions** [comment]
Yes
I also think adding JSON functionality could be the best possible route forward.

**Comment by deios0** [comment]
The JSON output is easy to add, just add the parameter '&fmt=json'

**Comment by freelancing-solutions** [comment]
I sure will thanks for the tip
