### ISSUE TITLE
Mutual funds data 

### ISSUE THREAD

**Issue by ghost** [EodHistoricalData/python-eodhistoricaldata#23]
I am trying to download historical data for this fund:

[https://eodhistoricaldata.com/financial-summary/LU0348926287.EUFUND](https://eodhistoricaldata.com/financial-summary/LU0348926287.EUFUND)

I used both:

get_eod_data("LU0348926287.EUFUND", 'EUFUND')

and  

get_eod_data("LU0348926287.EUFUND", 'US')

but I got the same error: 

`[Errno 404] Not Found: 'https://eodhistoricaldata.com/api/eod/LU0348926287.EUFUND.EUFUND?api_token=YOUR_HIDDEN_API&from=None&to=None'`

Any help?

**Comment by deios0** [comment]
![image](https://user-images.githubusercontent.com/1776997/137288228-6dbdede9-2b49-46ec-b635-eb5fe40a87c9.png)
Basically, already this URL should give the correct suggestion. But we will add more examples, thank you
